// This is an autogenerated file, see generate.py for edits. //

#define reg_setAilerons 0
#define reg_setElevator 1
#define reg_setRudder 2
#define reg_setThrottle 3
#define reg_setDropDoor 4
#define reg_setAutopilotState 5
#define reg_currentRoll 64
#define reg_currentPitch 65
#define reg_currentYaw 66
#define reg_dropDoorState 67
#define reg_onboardLoopSpeed 68 // Calculated execution loops per second
#define reg_currentControlState 69
#define reg_onboardRSSI 70 // Received signal strength (as a positive value, not negative)
#define reg_currentBattVoltage 71 // Voltage of battery (raw reading - processing to occur on PI)
#define reg_onboardCorruptedMessages 72
#define reg_onboardError 73 // 
#define reg_groundLoopSpeed 128
#define reg_groundRSSI 129

const int batteryVoltageReadingOffset = 600; // Provisional number!!
const int maxRadioMessageLength = 32; // Bytes
const int unlockDoorSignal = 100; // Signal to send from ground to unlock door.
const int lockDoorSignal = 200; // Signal to send from ground to lock door.
const int conflictingDropDoorMessageERR = 0; // Two messages sent to the drop door were both different
const int conflictingControlStateMessageERR = 1; // Two messages sent to change the control state were both different
