# Generate CommonConstants.h and CommonConstants.py to share registers between Pi and onboard Arduino

hFile = "ArduinoFiles/RC_Plane_Onboard_Control/CommonConstants.h"
pyFile = "GroundControl/CommonConstants.py"

# All registers in the form: (register number,register name,[comments])
registers = [
    # Ground to Plane registers:
    (0,"setAilerons"),
    (1,"setElevator"),
    (2,"setRudder"),
    (3,"setThrottle"),
    (4,"setDropDoor"),
    (5,"setAutopilotState"),

    # Plane to Ground registers:
    (64,"currentRoll"),
    (65,"currentPitch"),
    (66,"currentYaw"),
    (67,"dropDoorState"),
    (68,"onboardLoopTime","Calculated execution loops per second"),
    (69,"currentControlState"),
    (70,"onboardRSSI","Received signal strength (as a positive value, not negative)"),
    (71,"currentBattVoltage","Voltage of battery (raw reading - processing to occur on PI)"),
    (72,"onboardCorruptedMessages"),

    # Ground Arduino to PI registers:
    (128,"groundLoopSpeed"),
    (129,"groundRSSI"),
]

registersPrefix = "reg_"

# Shared constants in the form: (constant name,constant value,[comments])
constants = [
    ("batteryVoltageReadingOffset",600,"Provisional number!!"),
    ("maxRadioMessageLength",32,"Bytes"),
]

with open(hFile,"w") as h_file:
    h_file.write("// This is an autogenerated file //\n\n")
    for reg in registers:
        writeString = "#define "+registersPrefix+str(reg[1])+" "+str(reg[0])
        if len(reg) == 3: # i.e. if comment exists
            writeString += " // "+reg[2]
        h_file.write(writeString+"\n")

    h_file.write("\n")

    for const in constants:
        writeString = "const int "+str(const[0])+" = "+str(const[1])+";"
        if len(const) == 3: # i.e. if comment exists
            writeString += " // "+const[2]
        h_file.write(writeString+"\n")

with open(pyFile,"w") as py_file:
    py_file.write("## This is an autogenerated file ##\n\n")
    py_file.write("registers = {\n")
    for reg in registers:
        writeString = '    "'+str(reg[1])+'": '+str(reg[0])+','
        if len(reg) == 3: # i.e. if comment exists
            writeString += "   # "+reg[2]
        py_file.write(writeString+"\n")
    py_file.write("}\n\n")

    py_file.write("commonConstants = {\n")
    for const in constants:
        writeString = '    "'+str(const[0])+'": '+str(const[1])+','
        if len(reg) == 3: # i.e. if comment exists
            writeString += "   # "+const[2]
        py_file.write(writeString+"\n")

    py_file.write("}\n")
